"""
Write a programme where the computer randomly generates a number between 0 and 20.
The user needs to guess what the number is. If the user guesses wrong, tell them their guess is either too high,
or too low. This will get you started with the random library if you haven't already used it.
"""
import random
import time


class GuessNumber:
    def __str__(self):
        return "This is Guess Number Game"

    def game_play(self):
        try:
            user_input = int(input("Please enter your guess : "))
        except:
            return "Invalid Input, Input should be number"

        if not 0 <= user_input <= 20:
            return "Number should be in between 0-20"

        # Computer generated number
        number = random.randint(0, 20)
        print(f"Number generated by Computer is {number}")
        time.sleep(1)

        diff = abs(user_input - number)
        if number == user_input:
            return "Bingo !!! You won :)"
        elif user_input > number and diff >= 3:
            return "Try again, number guessed is too high"
        elif user_input > number and 1 <= diff < 3:
            return "Hard Luck !!!, you almost guessed the number tight :("
        elif user_input < number and diff >= 3:
            return "Try again, number guessed is too low"
        elif user_input < number and 1 <= diff < 3:
            return "Hard Luck !!!, you almost guessed the number tight :("


if __name__ == '__main__':
    game = GuessNumber()
    print(game)
    print(game.game_play())
